### ISSUE TITLE
Any support for clang

### ISSUE THREAD

**Issue by srikanth007m** [datadancer/HIAFuzz#1]
Have you tried it on kernels which got compiled with llvm/clang? the current kernel versions like 4.14+ are been supporting clang along with gcc. But most of the vendors suggesting to compile kernel using clang for better performance.

We have lldb for clang, which is similar to gdb for g++.

**Comment by datadancer** [comment]
I didn't tried it on kernels which got compiled with llvm/clang. Compiling kernels with llvm/clang is not practical yet. Do you have any resources helping?

**Comment by srikanth007m** [comment]
@datadancer - yes you can give it a try with linaro kernel which are been supported using clang.

$ make CC=clang HOSTCC=clang
Example cross compiling (arm64/aarch64):
$ ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- make CC=clang HOSTCC=clang
Link with LLD
$ make LD=ld.lld

**Comment by srikanth007m** [comment]
@datadancer - Also when i tried with some ioctls. I see it returned nothing in the folders. is there any way to extend?

handling nouveau_drm_ioctl
[{'payload': 'done.\\n', 'stream': 'stdout', 'type': 'console', 'message': None}, {'token': None, 'payload': None, 'stream': 'stdout', 'type': 'result', 'message': 'done'}, {'payload': 'info line nouveau_drm_ioctl\\n', 'stream': 'stdout', 'type': 'log', 'message': None}, {'payload': 'Function \\"nouveau_drm_ioctl\\" not defined.\\n', 'stream': 'stdout', 'type': 'log', 'message': None}, {'token': None, 'payload': {'msg': 'Function "nouveau_drm_ioctl" not defined.'}, 'stream': 'stdout', 'type': 'result', 'message': 'error'}]
handling drm_ioctl
[{'payload': 'done.\\n', 'stream': 'stdout', 'type': 'console', 'message': None}, {'token': None, 'payload': None, 'stream': 'stdout', 'type': 'result', 'message': 'done'}, {'payload': 'info line drm_ioctl\\n', 'stream': 'stdout', 'type': 'log', 'message': None}, {'payload': 'Function \\"drm_ioctl\\" not defined.\\n', 'stream': 'stdout', 'type': 'log', 'message': None}, {'token': None, 'payload': {'msg': 'Function "drm_ioctl" not defined.'}, 'stream': 'stdout', 'type': 'result', 'message': 'error'}]
All ioctl functions are found.

**Comment by datadancer** [comment]
The message 'Function "drm_ioctl" not defined.' suggests that gdb can not find definition in the binary image. Please confirm the function is compiled in the binary image.

**Comment by srikanth007m** [comment]
Yes, it got compiled. For your reference. 

0000000000000000 l    df *ABS*  0000000000000000 drm_ioctl.c
ffffff80091ba1b8 l     O .rodata        0000000000001290 drm_ioctls
ffffff8009774fb1 l     O __ksymtab_strings      0000000000000011 __kstrtab_drm_ioctl_permit
ffffff800972bb38 l     O __ksymtab      0000000000000010 __ksymtab_drm_ioctl_permit
ffffff8009774fc2 l     O __ksymtab_strings      0000000000000011 __kstrtab_drm_ioctl_kernel
ffffff800972bb28 l     O __ksymtab      0000000000000010 __ksymtab_drm_ioctl_kernel
ffffff8009774fd3 l     O __ksymtab_strings      000000000000000a __kstrtab_drm_ioctl
ffffff800972bb08 l     O __ksymtab      0000000000000010 __ksymtab_drm_ioctl
ffffff8009774fdd l     O __ksymtab_strings      0000000000000010 __kstrtab_drm_ioctl_flags
ffffff800972bb18 l     O __ksymtab      0000000000000010 __ksymtab_drm_ioctl_flags
ffffff80086426e0 g     F .text  0000000000000394 drm_ioctl
0000000057b6efe3 g       *ABS*  0000000000000000 __crc_drm_ioctl_flags
ffffff8008642a74 g     F .text  000000000000006c drm_ioctl_flags
00000000976127ce g       *ABS*  0000000000000000 __crc_drm_ioctl
ffffff8008642614 g     F .text  00000000000000cc drm_ioctl_kernel
ffffff8008642568 g     F .text  00000000000000ac drm_ioctl_permit
0000000095df0642 g       *ABS*  0000000000000000 __crc_drm_ioctl_kernel
00000000c879438d g       *ABS*  0000000000000000 __crc_drm_ioctl_permit

**Comment by srikanth007m** [comment]
Issue got resolved.

**Comment by aniucw** [comment]
> @datadancer - Also when i tried with some ioctls. I see it returned nothing in the folders. is there any way to extend?
> 
> handling nouveau_drm_ioctl [{'payload': 'done.\n', 'stream': 'stdout', 'type': 'console', 'message': None}, {'token': None, 'payload': None, 'stream': 'stdout', 'type': 'result', 'message': 'done'}, {'payload': 'info line nouveau_drm_ioctl\n', 'stream': 'stdout', 'type': 'log', 'message': None}, {'payload': 'Function \"nouveau_drm_ioctl\" not defined.\n', 'stream': 'stdout', 'type': 'log', 'message': None}, {'token': None, 'payload': {'msg': 'Function "nouveau_drm_ioctl" not defined.'}, 'stream': 'stdout', 'type': 'result', 'message': 'error'}] handling drm_ioctl [{'payload': 'done.\n', 'stream': 'stdout', 'type': 'console', 'message': None}, {'token': None, 'payload': None, 'stream': 'stdout', 'type': 'result', 'message': 'done'}, {'payload': 'info line drm_ioctl\n', 'stream': 'stdout', 'type': 'log', 'message': None}, {'payload': 'Function \"drm_ioctl\" not defined.\n', 'stream': 'stdout', 'type': 'log', 'message': None}, {'token': None, 'payload': {'msg': 'Function "drm_ioctl" not defined.'}, 'stream': 'stdout', 'type': 'result', 'message': 'error'}] All ioctl functions are found.

Can you tell me how you solved the problem? I have the same problem as you
