### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'DriverDevices/honor8_device_ioctl.txt'

### ISSUE THREAD

**Issue by srikanth007m** [datadancer/HIAFuzz#2]
@datadancer - While i am trying on my machine using below command. I see IOError even though the file is present. 

DriverDevices/honor8_device_ioctl.txt:5
Traceback (most recent call last):
  File "gdbioctl.py", line 258, in <module>
    main()
  File "gdbioctl.py", line 183, in main
    with open(parsed_args.device_ioctl_file, 'r') as ff:
FileNotFoundError: [Errno 2] No such file or directory: 'DriverDevices/honor8_device_ioctl.txt'

**Comment by datadancer** [comment]
Make sure honor8_device_ioctl.txt exist.




| |
lsb
邮箱：datadancer@163.com
|

签名由 网易邮箱大师 定制

On 12/23/2019 17:01, srikanth007m wrote:

@datadancer - While i am trying on my machine using below command. I see IOError even though the file is present.

DriverDevices/honor8_device_ioctl.txt:5
Traceback (most recent call last):
File "gdbioctl.py", line 258, in
main()
File "gdbioctl.py", line 183, in main
with open(parsed_args.device_ioctl_file, 'r') as ff:
FileNotFoundError: [Errno 2] No such file or directory: 'DriverDevices/honor8_device_ioctl.txt'

**Comment by srikanth007m** [comment]
@datadancer file is present in the same directory. seems we need to provide relative paths of the located files.
